/** Common IANA timezones for event form (grouped by region). */
export const TIMEZONE_OPTIONS: { value: string; label: string }[] = [
  { value: '', label: '— Select timezone —' },
  { value: 'America/Guayaquil', label: 'America/Guayaquil (Ecuador)' },
  { value: 'America/Bogota', label: 'America/Bogotá (Colombia)' },
  { value: 'America/Lima', label: 'America/Lima (Peru)' },
  { value: 'America/Panama', label: 'America/Panama' },
  { value: 'America/Mexico_City', label: 'America/Mexico City' },
  { value: 'America/New_York', label: 'America/New York (ET)' },
  { value: 'America/Chicago', label: 'America/Chicago (CT)' },
  { value: 'America/Denver', label: 'America/Denver (MT)' },
  { value: 'America/Los_Angeles', label: 'America/Los Angeles (PT)' },
  { value: 'America/Sao_Paulo', label: 'America/São Paulo (Brazil)' },
  { value: 'America/Buenos_Aires', label: 'America/Buenos Aires' },
  { value: 'America/Santiago', label: 'America/Santiago (Chile)' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid' },
  { value: 'Europe/London', label: 'Europe/London' },
  { value: 'Europe/Paris', label: 'Europe/Paris' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney' },
  { value: 'UTC', label: 'UTC' },
];
